version: '3'
services:
  frontend:
    build:
      context: ./frontend/employee-management-system # Path to the frontend directory
      dockerfile: Dockerfile
    ports:
      - 3000:3000  # Port mapping for the frontend
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: Employee_Management
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    ports:
      - 3306:3306  # Port mapping for MySQL

  backend:
    build:
      context: ./backend/EmployeeManagementSystemBackend  # Path to the backend directory
      dockerfile: Dockerfile
    ports:
      - 8888:8888  # Port mapping for the backend
    depends_on:
      - db

  
