version: '3'
services:
  frontend:
    build:
      context: ./frontend/employee-management-system # Path to the frontend directory
      dockerfile: Dockerfile
    ports:
      - 3000:3000  # Port mapping for the frontend
    depends_on:
      - backend
    networks:
      - frontend 
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: Employee_Management
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    ports:
      - 3306:3306  # Port mapping for MySQL
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

  backend:
    build:
      context: ./backend/EmployeeManagementSystemBackend  # Path to the backend directory
      dockerfile: Dockerfile
    ports:
      - 8888:8888  # Port mapping for the backend
    restart: always
    depends_on:
      - db
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/Employee_Management?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root 
      MYSQL_ROOT_PASSWORD: root
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:  

  
