# Use a base image with Java and Maven installed
FROM adoptopenjdk:17-jdk-hotspot

# Set the working directory inside the container
WORKDIR /app

# Copy the project files into the container
COPY . /app

# Build the application
RUN ./mvnw package -DskipTests

# Expose the port on which the application will run
EXPOSE 8888

# Set the command to run the application
CMD ["java", "-jar", "./target/backend.jar"]
