# Use a base image with Java 17 and Maven installed
FROM adoptopenjdk:17-jdk as builder
RUN apt-get update && apt-get install -y maven

# Set the working directory inside the container
WORKDIR /app

# Copy the project files into the container
COPY ./EmployeeManagementSystemBackend /app

# Build the application
RUN mvn -f /app/pom.xml clean package -DskipTests

# Use a new image for the runtime environment
FROM adoptopenjdk:17-jre-hotspot

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file from the builder image
COPY --from=builder /app/target/EmployeeManagementSystemBackend-0.0.1-SNAPSHOT.jar /app

# Expose the port on which the application will run
EXPOSE 8888

# Set the command to run the application
CMD ["java", "-jar", "EmployeeManagementSystemBackend-0.0.1-SNAPSHOT.jar"]

